name: sslexp
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge

dependencies:
  # 基本パッケージ
  - python=3.9.21
  - pip=25.0
  - numpy=2.0.2
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - h5py=3.13.0

  # PyTorch関連
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8  # Linux/NVIDIA GPUの場合
  - pytorch-mutex=1.0=cuda  # Linux/NVIDIA GPUの場合
  - torchtriton=3.1.0  # Linux/NVIDIA GPUの場合

  # 画像処理関連
  - pillow=11.1.0
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libtiff=4.5.1
  - openjpeg=2.5.2

  # 開発ツール
  - ipython=8.18.1
  - ipykernel=6.29.5
  - debugpy=1.8.14
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2

  # その他の基本ライブラリ
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=72.1.0
  - wheel=0.45.1
  - filelock=3.17.0
  - typing_extensions=4.13.2
  - networkx=3.2.1

  # pip経由のパッケージ
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.16
    - aiosignal==1.3.2
    - antlr4-python3-runtime==4.9.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - frozenlist==1.5.0
    - fsspec==2025.3.2
    - joblib==1.4.2
    - lightning-utilities==0.14.3
    - multidict==6.4.3
    - omegaconf==2.3.0
    - propcache==0.3.1
    - pytorch-lightning==2.2.1
    - pytz==2025.2
    - scipy==1.13.1
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - torchmetrics==1.3.1
    - tqdm==4.67.1
    - tzdata==2025.2
    - yarl==1.19.0

  # プラットフォーム固有の設定（コメントアウトして管理）
  # Linux CUDA用
  # - cuda-version=12.8
  # - cuda-runtime=11.8.0
  # - cuda-cudart=11.8.89
  # - cuda-cupti=11.8.87
  # - cuda-libraries=11.8.0
  # - cuda-nvrtc=11.8.89
  # - cuda-nvtx=11.8.86
  # - libcublas=11.11.3.6
  # - libcufft=10.9.0.58
  # - libcurand=10.3.9.90
  # - libcusolver=11.4.1.48
  # - libcusparse=11.7.5.86
  # - libnpp=11.8.0.86
  # - libnvjpeg=11.9.0.86