name: sslexp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # 基本パッケージ（プラットフォーム非依存）
  - python=3.9
  - pip
  - numpy
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - tqdm=4.67.1
  - omegaconf=2.3.0
  - pytorch-lightning=2.2.1
  - torchmetrics=1.3.1

  # 画像処理関連ライブラリ
  - libjpeg-turbo
  - libpng
  - libtiff
  - openjpeg
  - zlib

  # PyTorch関連（プラットフォーム依存）
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8  # CUDAバージョンは必要に応じて変更  Mac(Apple Silicon)では不要

  # 開発ツール
  - jupyter
  - ipykernel
  - black
  - flake8
  - mypy

  # その他の依存関係
  - pip:
    - aiohttp==3.11.16
    - fsspec==2025.3.2
    - joblib==1.4.2
    - lightning-utilities==0.14.3
    - propcache==0.3.1
    - pytz==2025.2
    - scipy==1.13.1
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tzdata==2025.2 